name = "ConfigurationsJUDI"
uuid = "2c8b6cec-2da9-47bf-8bb4-83702df661de"
authors = ["Grant Bruer gbruer15@gmail.com and contributors"]
version = "1.0.0-DEV"

[deps]
PackageExtensionCompat = "65ce6f38-6b18-4e1d-a461-8949797d7930"

[weakdeps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[extensions]
RandomExt = "Random"

[compat]
PackageExtensionCompat = "1"
julia = "1.8"
Random = "1.7"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
